name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Get tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Pack Newtonsoft adapter
        run: dotnet pack ./src/JsonPact.Newtonsoft --configuration Release --output ./artifacts/newtonsoft -p:PackageVersion=${TAG}

      - name: Pack System adapter
        run: dotnet pack ./src/JsonPact.System --configuration Release --output ./artifacts/system -p:PackageVersion=${TAG}

      # Store artifacts of the release
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./artifacts

      - name: Publish
        run: dotnet nuget push ./artifacts/**/*.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}
