name: release

on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v2

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./src/JsonPact.Newtonsoft --configuration Release -p:PackageVersion=${{github.ref_name}}

      #- name: Publish 
      #  run: dotnet nuget push JsonPact.Newtonsoft.${{github.ref_name}}.nupkg --api-key ${{NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
  