name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Get tag
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack ./src/JsonPact.Newtonsoft --configuration Release -p:PackageVersion=${{TAG}}

      #- name: Publish 
      #  run: dotnet nuget push JsonPact.Newtonsoft.${{TAG}}.nupkg --api-key ${{NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
  